service: qr-ticketing
frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: dev

  httpApi:
    cors:
      allowedOrigins:
        - "*"
      allowedMethods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allowedHeaders:
        - Content-Type
        - Authorization
      allowCredentials: false

  environment:
    USERS_TABLE: Users
    JWT_SECRET: ${/qr-ticketing/dev/JWT_SECRET~true}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:Query
            - dynamodb:Scan
          Resource:
            - arn:aws:dynamodb:${self:provider.region}:*:table/Users
            - arn:aws:dynamodb:${self:provider.region}:*:table/Users/index/*

functions:
  getUsers:
    handler: handlers/users/getUsers.main
    events:
      - httpApi:
          path: /users
          method: GET

  createUser:
    handler: handlers/users/createUser.main
    events:
      - httpApi:
          path: /users
          method: POST

  loginUser:
    handler: handlers/users/loginUser.main
    events:
      - httpApi:
          path: /login
          method: POST
